---
title: "Caracterización de la pérdida de función de los genes que codifican enzimas de la vía de isoprenoides de mevalonato (MVA) en <em>Arabidopsis thaliana</em>"
author: "Gimena_Vega"
format: html
html:
   toc: true
   toc-location: left
   embed-resources: true
   number-sections: true
   output-file: index
   theme: darkly
editor_options: 
  chunk_output_type: console
output: html_document



---


**Formulacion del problema**

<p align="justify">
La vía de mevalonato (MVA) es fundamental para la biosíntesis de isoprenoides, compuestos esenciales para el crecimiento, desarrollo y adaptación de plantas (Vranová et al., 2013). En <em>Arabidopsis thaliana</em>, se desconoce en grandes detalles el impacto que tiene la pérdida de función de los genes que codifican las enzimas de esta vía molecular, fisiológicos y fenotípicos de las plantas (Rodríguez-Concepción et al., 2004). Con ello nos podemos preguntar ¿Cómo afecta la pérdida de función de estos genes la expresión genética asociada a la vía de mevalonato (MVA)? ¿Qué cambios fenotípicos se manifiestan en líneas mutantes homocigotas? ¿Cuáles son las características genotípicas de estos mutantes? 
</p>

**Objetivo general**

<p align="justify">
Caracterizar de la pérdida de función de los genes que codifican enzimas de la vía de isoprenoides de mevalonato (MVA) en <em>Arabidopsis thaliana<em>.
</p>

**Objetivos especificos**

<p align="justify">
Genotipar mutantes de los de genes que codifican enzimas de la vía de isoprenoides de mevalonato (MVA) en <em>Arabidopsis thaliana</em>.

Evaluar el perfil de expresión génica de mutantes que codifican enzimas de la vía de isoprenoides de mevalonato (MVA) en <em>Arabidopsis thaliana</em>.

Fenotipar líneas mutantes homocigotas de los de genes que codifican enzimas de la vía de isoprenoides de mevalonato (MVA) en <em>Arabidopsis thaliana</em>.
</p>

REFERENCIAS BIBLIOGRAFICAS 

<p align="justify">
Vranová, E., Coman, D., & Gruissem, W. (2013). Network Analysis of the MVA and MEP Pathways for Isoprenoid Synthesis. Annual Review of Plant Biology, 64(1), 665-700. https://doi.org/10.1146/annurev-arplant-050312-120116
</p>

<p align="justify">
Rodríguez-Concepción, M., Forés, O., Martínez-García, J. F., González, V., Phillips, M. A., Ferrer, A., & Boronat, A. (2004). Distinct Light-Mediated Pathways Regulate the Biosynthesis and Exchange of Isoprenoid Precursors during Arabidopsis Seedling Development. The Plant Cell, 16(1), 144-156. https://doi.org/10.1105/tpc.016204
</p>

<p align="justify">
Kasahara, H., Hanada, A., Kuzuyama, T., Takagi, M., Kamiya, Y., & Yamaguchi, S. (2002). Contribution of the Mevalonate and Methylerythritol Phosphate Pathways to the Biosynthesis of Gibberellins inArabidopsis. Journal of Biological Chemistry, 277(47), 45188-45194. https://doi.org/10.1074/jbc.M208659200
</p>
